### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by luiq** [plutoyuxie/AE-SSIM#1]
您好，我想问一下，在代码运行到：
autoencoder.fit(data_train, epochs=EPOCHS, validation_data=data_valid, callbacks=[checkpoint, earlystopping])
报错：buffer_size must be greater than zero；
调试了还久，没解决，想请问一下：
1.训练的数据集文件夹是怎么排的？我是直接解压了用的；
2.cfg.aug_dir路径下的文件夹怎么排，里面的train_patches需要手动放训练集数据吗？
感谢！！

**Comment by plutoyuxie** [comment]
你好，train_patches是自动生成的。
如果设置了cfg.aug_dir，首次训练时也请在命令行传入--do_aug参数来执行数据增强操作。
你可能需要根据自己的情况改动options.py中的相关路径。

**Comment by luiq** [comment]
> 你好，train_patches是自动生成的。
> 如果设置了cfg.aug_dir，首次训练时也请在命令行传入--do_aug参数来执行数据增强操作。
> 你可能需要根据自己的情况改动options.py中的相关路径。
谢谢您的及时回复，我调试后发现是我GPU内存不够导致的，我的GPU是2080ti， 显存是11G的，我把batch_size改为20能勉强跑起来，但是感觉这样训练效果不好，所以您那有什么调试意见吗？新入行的小白，请您多多指教。
