### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by luiq** [plutoyuxie/AE-SSIM#2]
谢谢您的及时回复，我调试后发现是我GPU内存不够导致的，我的GPU是2080ti， 显存是11G的，我把batch_size改为20能勉强跑起来，但是感觉这样训练效果不好，所以您那有什么调试意见吗？新入行的小白，请您多多指教。

**Comment by plutoyuxie** [comment]
你好，你可以将自动保存的参数设置文件opt.txt里的内容贴出来，这样我好看出哪里有问题。
