### ISSUE TITLE
opt.txt

### ISSUE THREAD

**Issue by luiq** [plutoyuxie/AE-SSIM#3]
------------ Options -------------
aug_dir: C:/Users/Machine/Desktop/liuQ/6.25/code1/AE_results/carpet/train_patches
augment_num: 100
batch_size: 20
chechpoint_dir: C:/Users/Machine/Desktop/liuQ/6.25/code1/AE_results/carpet/chechpoints/ssim_loss
decay: 1e-05
depress_edge_pixel: 10
depress_edge_ratio: 0.2
do_aug: False
early_stop_n: 50
epochs: 100
flc: 32
grayscale: False
im_resize: 256
input_channel: 3
l1_threshold: None
loss: ssim_loss
lr: 0.0002
name: carpet
p_crop: 1
p_horizonal_flip: 0.3
p_rotate: 0.3
p_rotate_crop: 1.0
p_vertical_flip: 0.3
patch_size: 32
percent: 98.0
rotate_angle_vari: 45.0
save_dir: C:/Users/Machine/Desktop/liuQ/6.25/code1/AE_results/carpet/reconst/ssim_l1_metric_ssim_loss
save_model_frequency: 1
save_snapshot: False
simplified: False
ssim_threshold: None
ssim_win_size: 11
stride: 32
sub_folder: ['000.png', '001.png', '002.png', '003.png', '004.png', '005.png', '006.png', '007.png', '008.png', '009.png', '010.png', '011.png', '012.png', '013.png', '014.png', '015.png', '016.png', '017.png', '018.png']
test_dir: C:/Users/Machine/Desktop/liuQ/6.25/code1/data/carpet/test/color
train_data_dir: C:/Users/Machine/Desktop/liuQ/6.25/code1/data/carpet/train/good
valid_data_ratio: 0.2
weight: 10
weight_file: None
z_dim: 512
-------------- End ----------------
这是哪个您说的那个文件，可以加一下好友吗？ QQ：1103511435

**Comment by luiq** [comment]
> ------------ Options -------------
> aug_dir: C:/Users/Machine/Desktop/liuQ/6.25/code1/AE_results/carpet/train_patches
> augment_num: 100
> batch_size: 20
> chechpoint_dir: C:/Users/Machine/Desktop/liuQ/6.25/code1/AE_results/carpet/chechpoints/ssim_loss
> decay: 1e-05
> depress_edge_pixel: 10
> depress_edge_ratio: 0.2
> do_aug: False
> early_stop_n: 50
> epochs: 100
> flc: 32
> grayscale: False
> im_resize: 256
> input_channel: 3
> l1_threshold: None
> loss: ssim_loss
> lr: 0.0002
> name: carpet
> p_crop: 1
> p_horizonal_flip: 0.3
> p_rotate: 0.3
> p_rotate_crop: 1.0
> p_vertical_flip: 0.3
> patch_size: 32
> percent: 98.0
> rotate_angle_vari: 45.0
> save_dir: C:/Users/Machine/Desktop/liuQ/6.25/code1/AE_results/carpet/reconst/ssim_l1_metric_ssim_loss
> save_model_frequency: 1
> save_snapshot: False
> simplified: False
> ssim_threshold: None
> ssim_win_size: 11
> stride: 32
> sub_folder: ['000.png', '001.png', '002.png', '003.png', '004.png', '005.png', '006.png', '007.png', '008.png', '009.png', '010.png', '011.png', '012.png', '013.png', '014.png', '015.png', '016.png', '017.png', '018.png']
> test_dir: C:/Users/Machine/Desktop/liuQ/6.25/code1/data/carpet/test/color
> train_data_dir: C:/Users/Machine/Desktop/liuQ/6.25/code1/data/carpet/train/good
> valid_data_ratio: 0.2
> weight: 10
> weight_file: None
> z_dim: 512
> -------------- End ----------------
> 这是哪个您说的那个文件，可以加一下好友吗？ QQ：1103511435

**Comment by plutoyuxie** [comment]
已解决，问题关闭。
