### ISSUE TITLE
你好，请问运用这个数据集和代码重建的图很模糊，和image里的效果相差甚远，是什么原因呢？谢谢。

### ISSUE THREAD

**Issue by SunnysideBao** [plutoyuxie/AE-SSIM#4]

**Comment by plutoyuxie** [comment]
您好，image里的grid重建结果，我的设置是
epoch 200次；
数据增强augment_num: 10000；
z_dim: 100；
希望能对您有帮助。

**Comment by SunnysideBao** [comment]
谢谢您的回复，训练的数据集您用的是grid里面good的数据吗？要求输入大小是128*128,您是将它分块还是等比例缩小呢？

**Comment by plutoyuxie** [comment]
你好，是的，用无缺陷数据训练。
先缩放再随机裁剪，数据增强有旋转翻转等。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sunnyside Bao <notifications@github.com&gt;
发送时间: 2020年7月12日 09:22
抄送: plutoyuxie <346929320@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[plutoyuxie/AutoEncoder-SSIM-for-unsupervised-anomaly-detection-] 你好，请问运用这个数据集和代码重建的图很模糊，和image里的效果相差甚远，是什么原因呢？谢谢。 (#4)





 
谢谢您的回复，训练的数据集您用的是grid里面good的数据吗？要求输入大小是128*128,您是将它分块还是等比例缩小呢？

**Comment by SunnysideBao** [comment]
谢谢，原本的像素值为1024*1024，您是缩放到什么程度进行裁剪到128*128呢？

**Comment by plutoyuxie** [comment]
256x256



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sunnyside Bao <notifications@github.com&gt;
发送时间: 2020年7月12日 09:40
抄送: plutoyuxie <346929320@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[plutoyuxie/AutoEncoder-SSIM-for-unsupervised-anomaly-detection-] 你好，请问运用这个数据集和代码重建的图很模糊，和image里的效果相差甚远，是什么原因呢？谢谢。 (#4)





 
谢谢，原本的像素值为10241024，您是缩放到什么程度进行裁剪到128128呢？
