### ISSUE TITLE
指标测试问题

### ISSUE THREAD

**Issue by interstate50** [plutoyuxie/AE-SSIM#5]
作者你好，请问你测试过复现的代码在MVTec上的指标吗？我跑了下，比论文里面展示的估计要低个5~10个点？

**Comment by plutoyuxie** [comment]
对于object类型数据，我按照论文重建全图，而非基于patch重建，最新的代码没有上传。基本上是按照paper设置，完整测试了mvtec ad，其中grid/toothbrush/bottle精度较高，tile/cable等精度较低。稍后我将把最新代码和实际测试统计表更新出来。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jinlei Hou <notifications@github.com&gt;
发送时间: 2020年7月23日 18:59
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[plutoyuxie/AutoEncoder-SSIM-for-unsupervised-anomaly-detection-] 指标测试问题 (#5)





 
作者你好，请问你测试过复现的代码在MVTec上的指标吗？我跑了下，比论文里面展示的估计要低个5~10个点？

**Comment by plutoyuxie** [comment]
@interstate50 
我已上传最新代码和测试统计表。在某些场景，特别是金属材质、高频纹理、液体胶体等，AE-SSIM重建质量不高，从而导致分割精度下降明显。
