### ISSUE TITLE
请问，既然需要用mask，为什么还叫无监督呢？

### ISSUE THREAD

**Issue by FrankFirstLearn** [plutoyuxie/AE-SSIM#6]

**Comment by plutoyuxie** [comment]
您好，这里的mask是后处理用到的背景蒙版，不是必须的。
训练过程只用到正样本，没有使用groundtruth label信息。
请您先看看代码。

**Comment by FrankFirstLearn** [comment]
那我执行 test.py的时候，为什么没有那些mask文件，就会报错呢？代码有点多，我一时看不明白，对了，请问你那个一开始那一大堆信息怎么不显示啊？谢谢😁



---原始邮件---
发件人: "plutoyuxie"<notifications@github.com&gt;
发送时间: 2020年8月4日(周二) 中午1:25
收件人: "plutoyuxie/AutoEncoder-SSIM-for-unsupervised-anomaly-detection-"<AutoEncoder-SSIM-for-unsupervised-anomaly-detection-@noreply.github.com&gt;;
抄送: "FrankFirstLearn"<2414345823@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [plutoyuxie/AutoEncoder-SSIM-for-unsupervised-anomaly-detection-] 请问，既然需要用mask，为什么还叫无监督呢？ (#6)




 
您好，这里的mask是后处理用到的背景蒙版，不是必须的。
 训练过程只用到正样本，没有使用groundtruth label信息。
 请您先看看代码。
