### ISSUE TITLE
陷入局部最优

### ISSUE THREAD

**Issue by smiler96** [plutoyuxie/AE-SSIM#9]
谢谢您的开源代码！我发现在conv或者deconv后面不加batchnormalization的话，训练出来的结果都是灰色的，陷入了局部最优。加了BatchNormalization之后，就有了重建的效果，请问您在跑实验的时候会出现这样的问题吗？

**Comment by plutoyuxie** [comment]
> 谢谢您的开源代码！我发现在conv或者deconv后面不加batchnormalization的话，训练出来的结果都是灰色的，陷入了局部最优。加了BatchNormalization之后，就有了重建的效果，请问您在跑实验的时候会出现这样的问题吗？

嗨，我跑实验时没发现这个问题。。结果是灰色的可能是输出未规约到0-255之间？使用BN会加速收敛，不过也可能带来其他问题。

**Comment by smiler96** [comment]
> > 谢谢您的开源代码！我发现在conv或者deconv后面不加batchnormalization的话，训练出来的结果都是灰色的，陷入了局部最优。加了BatchNormalization之后，就有了重建的效果，请问您在跑实验的时候会出现这样的问题吗？
> 
> 嗨，我跑实验时没发现这个问题。。结果是灰色的可能是输出未规约到0-255之间？使用BN会加速收敛，不过也可能带来其他问题。

我用的pytorch写的，模型输入数据是直接/255.0 归一化到0~1，最后的激活层加了一层Sigmoid。应该是向您说的一样，加了bn加速了收敛。
